# gigshield/backend/alembic/script.py.mako

"""initial_schema

Revision ID: 02c76db1be70
Revises: ee5ddadcd60f
Create Date: 2026-03-20 10:16:32.105161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '02c76db1be70'
down_revision: Union[str, None] = 'ee5ddadcd60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('workers', 'created_at')
    op.drop_column('zones', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('workers', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###