# gigshield/backend/alembic/script.py.mako

"""initial_schema

Revision ID: ee5ddadcd60f
Revises: 
Create Date: 2026-03-20 09:35:46.480758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee5ddadcd60f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=10), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('is_mocked', sa.Boolean(), nullable=True),
    sa.Column('logged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('centroid_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('centroid_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_km', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('risk_tier', sa.String(length=10), nullable=True),
    sa.Column('seasonal_disruption_days', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('disruption_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('peak_zdi', sa.Integer(), nullable=True),
    sa.Column('peak_level', sa.String(length=10), nullable=True),
    sa.Column('affected_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('signal_readings',
    sa.Column('reading_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('normalized_score', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('is_mocked', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=True),
    sa.Column('primary_zone_id', sa.String(length=10), nullable=False),
    sa.Column('income_tier', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('kyc_status', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('aadhaar_hash'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('zdi_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=10), nullable=False),
    sa.Column('zdi_score', sa.Integer(), nullable=False),
    sa.Column('disruption_level', sa.String(length=10), nullable=False),
    sa.Column('payout_pct', sa.Integer(), nullable=False),
    sa.Column('rain_component', sa.Integer(), nullable=True),
    sa.Column('outage_component', sa.Integer(), nullable=True),
    sa.Column('traffic_component', sa.Integer(), nullable=True),
    sa.Column('aqi_component', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=10), nullable=False),
    sa.Column('income_tier', sa.Integer(), nullable=False),
    sa.Column('weekly_premium_inr', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('weekly_payout_cap', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('season_at_purchase', sa.String(length=15), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('lookback_exclusion_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('disruption_event_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=10), nullable=False),
    sa.Column('disruption_level', sa.String(length=10), nullable=False),
    sa.Column('payout_pct', sa.Integer(), nullable=False),
    sa.Column('affected_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('working_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gross_payout_inr', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cap_applied', sa.Boolean(), nullable=True),
    sa.Column('final_payout_inr', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fraud_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disruption_event_id'], ['disruption_events.event_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('payouts',
    sa.Column('payout_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('is_mocked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('initiated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('settled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('payout_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    op.drop_table('claims')
    op.drop_table('policies')
    op.drop_table('zdi_snapshots')
    op.drop_table('workers')
    op.drop_table('signal_readings')
    op.drop_table('disruption_events')
    op.drop_table('zones')
    op.drop_table('audit_log')
    # ### end Alembic commands ###